### ISSUE TITLE
multilingual / turn off option

### ISSUE THREAD

**Issue by tbba** [rockettpw/jumplinks#15]
Previous version of the Plugin had been multilanguage friendly in a way that the language part of the target website was shown /de/, /en/) - often in the wrong language but anyway.
Now the language part is left out which leads to an invalid link (which is hurting SEO).

Unfortunately I cannot just deinstall the module as this would whipe out my settings with all links from the database. So a "turn off" switch in the module would be useful for me until a real language handling will be added eventually in the forth coming version.

**Comment by mikerockett** [comment]
Adding this functionality in v1 means a schema change, which I'm not keen on due to the various bugs. If you like, I can add functionality so that if a double-exclamation mark is added to the front of the Source, the jumplink will be skipped. That way, I don't have to do a schema change. Keen?

The state toggler has been implemented in v2 already (just for reference):

![toggler](https://cloud.githubusercontent.com/assets/4586280/18231281/130830bc-72b6-11e6-9dda-87b779f8ad61.gif)

**Comment by tbba** [comment]
I fully understand that you do not want to work much further on V1 while V2 is nearly there.
I probable will not add !! at every source line. Too many links, too many clicks :-)
I just wanted to stop the execution of the module entirely without uninstalling it (so, just in case V2 will have an importer for the V1 links, the links would be still in the database). - But never mind. I will find a workaround...
The toggler looks interesting (looks a bit like a radio button right now)

**Comment by mikerockett** [comment]
Ah, sorry - was far too interested in getting *something* done and did not think that you might have many jumplinks. Nonetheless, I'm keeping the workaround there for whoever may need it.

v2 will definitely import jumplinks from v1 and make the necessary conversions to the new format as it goes along. When it's done, it will remove the old tables (the names of the tables have changed in v2).

I think Adrian has made something that allows you to disable modules one by one... But I'll add in a module-toggler for you - really, I don't want to be in a position where the module is affecting your SEO, and you have to find workarounds to prevent that from happening.

Initially, it was a round green button, but it looked to contrasted and distracting, which is why I changed it to an outlined circle. I did also think that it looked like a radio button, but, at the end of the day, when you realise how it works, then it doesn't look so much like one anymore. :wink:
